apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::500769580437:role/UdacityFlaskDeployCBKubectlRole
      username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::500769580437:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ROY72F4BQRUY
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-29T19:40:50Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1304"
  uid: c3601162-3615-4929-acd1-b08940f30552
